=== arkadiuszdom/XML_DTD_CSS_XSD/ranking.dtd
<!DOCTYPE ranking
[
<!ELEMENT ranking (header,genres,positions)>

	<!ELEMENT header (task_name,author+)>
		<!ELEMENT task_name (#PCDATA)>

		<!ELEMENT author (#PCDATA)>


	<!ELEMENT genres (genre*)>

		<!ELEMENT genre (#PCDATA)>
		<!ATTLIST genre genre_id ID #REQUIRED>

	<!ELEMENT positions (position*)>

		<!ELEMENT position (number,name,genreName,rating,age,releaseDate,predecessor?)>

			<!ELEMENT number (#PCDATA)>
			<!ATTLIST number top_three ID #IMPLIED>

			<!ELEMENT name (#PCDATA)>

			<!ELEMENT genreName (#PCDATA)>
			<!ATTLIST genreName genre_id IDREF #REQUIRED>
			<!ATTLIST genreName color NMTOKEN "black">

			<!ELEMENT rating (#PCDATA)>

			<!ELEMENT age (#PCDATA)>
			<!ATTLIST age minimum (12|16|18) #REQUIRED>

			<!ELEMENT releaseDate (#PCDATA)>

			<!ELEMENT predecessor (name)>
]>

=== arkadiuszdom/XML_DTD_CSS_XSD/ranking.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE ranking SYSTEM "ranking.dtd">
<?xml-stylesheet type="text/css" href="ranking.css" ?>
<ranking>
	<positions>
		<position>
			<number>
				1
			</number>
			<name>
				Game1
			</name>
			<genreName>
				FPS
			</genreName>
			<rating>
				5.0
			</rating>
			<age>
				18+
			</age>
			<releaseDate>
				12.05.2018
			</releaseDate>
		</position>
	</positions>
	<genres>
		<genre genreId="1">
			<icon/>
			<name>
				FPS
			</name>
		</genre>
	</genres>
</ranking>
